logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = "client-spoof spoof-app-version spoof-signature-verification custom-branding vanced-microg-support minimized-playback open-links-directly open-links-externally return-youtube-dislike seekbar-tapping sponsorblock swipe-controls video-ads hide-ads downloads"
version = "auto"
exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
