logging-to-file = false
enable-magisk-update = true
build-mindetach-module = false

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = "client-spoof spoof-app-version spoof-signature-verification custom-branding vanced-microg-support minimized-playback open-links-directly open-links-externally return-youtube-dislike seekbar-tapping sponsorblock swipe-controls video-ads hide-ads downloads"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
